### PR TITLE
fix: removed legacy jasmine wdio helper

### PR DESCRIPTION
**Pull request by pozil**
Removed legacy Jasmine wdio helper that is no longer needed since wdio@7 as per comments in https://github.com/salesforce/utam-js-recipes/pull/102

### CODE REVIEW

**Comment by pozil** [comment]
@olivier-martin-sf feel free to review.

**Comment by olivier-martin-sf** [comment]
@pozil do you mind cleaning it from `wdio.conf.mobilebase.js` as well?

**Comment by pozil** [comment]
Sorry I missed that one. Done.

**Review by olivier-martin-sf — APPROVED** [review]
Thank you so much for your contribution helping us keeping the project up to date

**Pull request merged**
